import Head from 'next/head'
import { useState } from 'react';
import Image from 'next/image'
import { Inter } from '@next/font/google'

import CButton from '../src/components/CButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [inputVal, setInputValue] = useState(0);
  const [firstInput, setFirstInput] = useState(0);
  //console.log("🚀 ~ file: index.js:13 ~ Home ~ firstInput", firstInput)
  const [secondInput, setSecondInput] = useState(0);
  const [operator, setOperator] = useState('none');
  const [result, setResult] = useState(0);


  const clearAll = (e) => {
    setFirstInput(0);
    setSecondInput(0);
    setOperator('none')
    setResult(0)
    console.log('all were reset!')
  }

  const handleClick = (e) => {
    let input = e.target.value;
    if (input == '/' || input == 'x' || input == '-' || input == '+' || input == '=' || input == 'C') {
      switch (input) {
        case '/': setOperator('/'); break;
        case 'x': setOperator('x'); break;
        case '-': setOperator('-'); break;
        case '+': setOperator('+'); break;
        default: clearAll(); break;
      }
      input = input;
    } else {
      input = parseInt(input);
      if (operator == 'none') {
        setFirstInput(input);
      } else {
        setSecondInput(input);
      }

    }
    console.log("🚀 ~ file: index.js:29 ~ handleClick ~ input", input)
    if (input == '=') {     
      console.log("🚀 ~ file: index.js:49 ~ handleClick ~ tmpResult", input)
      switch (operator) {
        case '/': setResult(firstInput / secondInput); break;
        case 'x': setResult(firstInput * secondInput); break;
        case '-': setResult(firstInput - secondInput); break;
        case '+': setResult(firstInput + secondInput); break;      }
      
    }

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>

        <h1>Calculator</h1>
        <input value={inputVal} onChange={(e) => { setInputValue(e.target.value) }} />
        <div className='button-group'>
          <CButton label='C' value='C' handleClick={handleClick} color="black"></CButton>
          <CButton label=' '></CButton>
          <CButton label=' '></CButton>
          <CButton label='/' value="/" handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='1' value='1' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='2' value='2' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='3' value='3' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='x' value='x' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='4' value='4' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='5' value='5' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='6' value='6' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='-' value='-' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='7' value='7' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='8' value='8' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='9' value='9' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='+' value='+' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label=' ' value='+' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='0' value='0' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label=' ' value='' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
          <CButton label='=' value='=' handleClick={handleClick} setFirstInput={setFirstInput} setSecondInput={setSecondInput} color="black"></CButton>
        </div>
        <div className="result">{result}</div>



      </main>
    </>
  )
}
